- name: disable {{ packageName }} module
  ansible.builtin.shell: dnf module disable {{ packageName}} -y
  become: true

- name: enable {{ packageName }} module {{ packageversion }}
  ansible.builtin.shell: dnf module enable {{ packageName }}:{{ packageversion}} -y
  become: true

- name: installing {{ packageName }}
  ansible.builtin.shell: dnf install {{ packageName}} -y
  become: true

- name: Configuring the hostName 
  ansible.builtin.shell: set-hostname {{ component }}-{{ env }}
  become: true
  
- name: creating the {{ component }} user
  ansible.builtin.user:
    name: "{{ appuser }}"
    createhome: yes

- name: Cleanup of the  "{{ appdirectory }}" content
  ansible.builtin.file:
    path: "{{ appdirectory }}"
    state: absent


- name: creating the {{ component }} directory
  ansible.builtin.file:
    path: "{{ appdirectory }}"
    state: directory

- name: Download and extract frontend
  ansible.builtin.unarchive:
    src: "{{ url }}"
    dest: "{{ appdirectory }}"
    remote_src: yes 

- name: generating the artifacts
  community.general.npm:
   path: "{{ appdirectory }}"

- name: configuring the {{ component }} service
  ansible.builtin.template:
    src: "{{ component }}.service"
    dest: "/etc/systemd/system/{{ component }}.service"

- name: configuring the mongodb repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: installing mongodbshell
  ansible.builtin.package:
    name: mongodb-mongosh
    state: present    

- name: Starting "{{ component }}" service
  ansible.builtin.service:
    name: "{{ component }}"
    enabled: yes
    state: restarted
    daemon_reload: yes  

- name: injecting mongodb schema
  ansible.builtin.shell: "mongo --host mongodb-{{ env }}.roboshope.shop </app/db/master-data.js"

- name: Configuring the hostName 
  ansible.builtin.shell: set-hostname {{ component}}-{{ env }}
  become: true
