- name: configuring the {{component}} repo
  ansible.builtin.copy:
    src: "{{ component }}.repo"
    dest: "/etc/yum.repos.d/{{ component }}.repo"
   

- name: installing the {{packegeName}} 
  ansible.builtin.package:
    name: "{{ packageName }}"
    state: present

- name: Starting "{{ packagename }}" service
  ansible.builtin.service:
    name: mongod
    enabled: yes
    state: restarted
