- name: Installing mysqlShell
  ansible.builtin.package:
    name: mysql
    state: present

- name: Injecting Schema for {{ component }} service
  loop: "{{ schema }}"
  ansible.builtin.shell: mysql -h mysql-{{ env }}.roboshope.shop -uroot -pRoboShop@1 < /app/db/{{ item }}