- name: disable the default nginx module
  become: yes
  ansible.builtin.dnf_module:
    name: nginx
    state: disabled

- name: enable nginx 1.24 module
  become: yes
  ansible.builtin.dnf_module:
    name: nginx:1.24
    state: enabled

- name: install nginx
  become: yes
  ansible.builtin.package:
    name: nginx
    state: present

    -name:starting nginx service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
      