- name: Disabling the default nginx module
  ansible.builtin.shell: dnf module disable nginx -y

  
- name: Enabling the default nginx version 
  ansible.builtin.shell: dnf module enable nginx:1.24 -y
  

- name: Installing Nginx 
  ansible.builtin.package:
    name: nginx
    state: present
  
- name: Starting Nginx service
  ansible.builtin.service:
    name: nginx
    enabled: yes
    state: started

- name: Download and extract frontend
  ansible.builtin.unarchive:
    src: "{{ url }}"
    dest: /tmp/
    remote_src: yes           # If yes, download from the URL mentioned in src machine, if no, copy from local machine to remote machine

- name: Cleanup of the default Nginx content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent
    
- name: Configuring the hostName 
  ansible.builtin.shell: set-hostname frontend-{{ env }}
  become: true
